//-------------------------------------------------------------------------------
// NOTE: this file is autogenerated:
//    * From /mnt/c/Users/pevha/wsl/github/hdlskel/pip/skmap/src/skmap/code_generator_cpp.py
//    * On 2026-09-27 04:54:38.279645 
//    * Using HDLSkel SkMap v1.1.0
//    * For test_skmap_tree_module TBTrMod v1
//    * Checksum 0x1AD7
//-------------------------------------------------------------------------------

#include "hdlskel/skmap/autogen_test/test_skmap_tree_module.hpp"

namespace hdlskel::skmap::autogen {

bool TestSkmapTreeModule::registered = Module::register_module(std::make_shared<TestSkmapTreeModule>());

void TestSkmapTreeModule::init_reg_map_k() {
    m_k_TREE_DEPTH = make_reg_k("TREE_DEPTH", make_ValueType(ValueKind::uint_, 8), "Tree depth");
    add_reg_k(m_k_TREE_DEPTH);
    m_k_TREE_WIDTH = make_reg_k("TREE_WIDTH", make_ValueType(ValueKind::uint_, 8), "Tree width");
    add_reg_k(m_k_TREE_WIDTH);
}

void TestSkmapTreeModule::init_reg_map_var() {
    m_var_trigger_flags = make_reg("trigger_flags", Acc::wt, make_ValueType(ValueKind::bits_, 5), "Trigger asserts");
    add_reg_var(m_var_trigger_flags);
    m_var_flag_debug = make_r_flag("flag_debug", 0, Ass::debug, "Flag 0");
    m_var_flag_info = make_r_flag("flag_info", 1, Ass::info, "Flag 1");
    m_var_flag_warn = make_r_flag("flag_warn", 2, Ass::warn, "Flag 2");
    m_var_flag_error = make_r_flag("flag_error", 3, Ass::error, "Flag 3");
    m_var_flag_fatal = make_r_flag("flag_fatal", 4, Ass::fatal, "Flag 4");
    std::vector<std::shared_ptr<RFlag>> m_var_flags_flags;
    push_back_flag(m_var_flags_flags, m_var_flag_debug);
    push_back_flag(m_var_flags_flags, m_var_flag_info);
    push_back_flag(m_var_flags_flags, m_var_flag_warn);
    push_back_flag(m_var_flags_flags, m_var_flag_error);
    push_back_flag(m_var_flags_flags, m_var_flag_fatal);
    m_var_flags = make_reg_flags("flags", Acc::rc, 5, m_var_flags_flags, "RC flags");
    add_reg_var(m_var_flags);
}
}
