#!/usr/bin/env python3

import argparse
from pathlib import Path
from datetime import datetime
from typing import Literal

from code_generator_parse_recipe import parse_recipe_file, RecipeK, RecipeVar, RecipeReg
from basic import promote_to_sw_w, ceil_div
from basic_types import Acc, Ass, ValueKind, ValueType, SKMAP_VER_STR

def port_name_trig(port_name : str):
    return port_name[:-2]+"_trigger_o"

def port_name_clear(port_name : str):
    return port_name[:-2]+"_clear_o"

def port_name(name : str, direction : Literal['in', 'out']):
    port_ext_in = "_i"
    port_ext_out = "_o"
    port_ext_bad = port_ext_in  if direction == 'in'  else port_ext_out
    port_ext     = port_ext_out if direction == 'out' else port_ext_in

    assert not name.endswith(port_ext_bad)
    port_name = name
    if not name.endswith(port_ext):
        port_name += port_ext
    return port_name

def var_name(name : str):
    return name + "_v"

def k_type_to_vhdl_str(t : ValueType, basic_ports:bool=False) -> str:
    elem_rng = f"({t.width}-1 downto 0)"
    if basic_ports:
        if t.is_vec:
            assert False, "yet to be implemented" 
        else:
            match t.kind:
                case ValueKind.uint: return "natural"
                case ValueKind.sint: return "integer"
                case ValueKind.char: return "std_logic_vector(7 downto 0)"
                case ValueKind.bits: return f"std_logic_vector{elem_rng}"
                case ValueKind.flag: return f"std_logic_vector{elem_rng}"
    else:
        if t.is_vec:
            vec_rng = f"(0 to {t.vec_len}-1)"
            str_rng = f"(1 to {t.vec_len})"
            flg_rng = f"({t.width}-1 downto 0)"
            match t.kind:
                case ValueKind.uint: return f"integer_vector{vec_rng}"
                case ValueKind.sint: return f"integer_vector{vec_rng}"
                case ValueKind.char: return f"string{str_rng}"
                case ValueKind.bits: return f"vec_slv_t{vec_rng}{elem_rng}"
                case ValueKind.flag: return f"std_logic_vector{flg_rng}"
        else:
            match t.kind:
                case ValueKind.uint: return "natural"
                case ValueKind.sint: return "integer"
                case ValueKind.char: return "character"
                case ValueKind.bits: return f"std_logic_vector{elem_rng}"
                case ValueKind.flag: return f"std_logic_vector{elem_rng}"

def var_type_to_vhdl_str(t : ValueType, basic_ports:bool=False) -> str:
    elem_rng = f"({t.width}-1 downto 0)"
    if basic_ports:
        if t.is_vec:
            assert False, "yet to be implemented" 
        else:
            return f"std_logic_vector{elem_rng}"
    else:
        if t.is_vec:
            vec_rng = f"(0 to {t.vec_len}-1)"
            str_rng = f"(1 to {t.vec_len})"
            flg_rng = f"({t.vec_len}*{t.width}-1 downto 0)"
            match t.kind:
                case ValueKind.uint: return f"vec_unsigned_t{vec_rng}{elem_rng}"
                case ValueKind.sint: return f"vec_signed_t{vec_rng}{elem_rng}"
                case ValueKind.char: return f"string{str_rng}"
                case ValueKind.bits: return f"vec_slv_t{vec_rng}{elem_rng}"
                case ValueKind.flag: return f"std_logic_vector{flg_rng}"
        else:
            match t.kind:
                case ValueKind.uint: return f"unsigned{elem_rng}"
                case ValueKind.sint: return f"signed{elem_rng}"
                case ValueKind.char: return f"character"
                case ValueKind.bits: return f"std_logic_vector{elem_rng}"
                case ValueKind.flag: return f"std_logic_vector{elem_rng}"

def regs_len_str(regs : list[RecipeReg], name : str, k : bool = False) -> str:
    s = (f"""
  function get_{name} return natural is
    variable byte_idx : natural := 0;
  begin\n""")
    for r in regs:
        s += (f"    skmap_map_acc_byte_inc(byte_idx, VAL_W=>{r.t.width}")
        if not k:
            s += (", BYTE_ALIGN=>BYTE_ALIGN")
        if r.t.is_vec:
            s += (f", VEC_LEN=>{r.t.vec_len}");
        s += (f"); -- {r.name}\n")
    s += (f"""    return ceil_div(byte_idx, 4);
  end function;
  constant {name} : natural := get_{name};\n""")
    return s;



def generate_vhdl_module(recipe_file : Path, vhdl_file : Path):
    recipe = parse_recipe_file(recipe_file)

    basic_ports : bool = recipe.fw_opts.ports_use_basic_types
    hdlskel_lib : str  = recipe.fw_opts.hdlskel_vhdl_lib

    with open(vhdl_file, 'w') as vhdl_f:
        # write start 
        vhdl_f.write(f""" --------------------------------------------------------------------------------
-- NOTE: this file is autogenerated:
--    * From {__file__}
--    * On {datetime.now()} 
--    * Using HDLSkel SkMap {SKMAP_VER_STR}
--    * For {recipe.name} {recipe.id} v{recipe.version}
--    * Checksum {recipe.checksum_str()}
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;\n""")
        if hdlskel_lib != 'work':
            vhdl_f.write(f"""
library {hdlskel_lib};""")

        vhdl_f.write(f"""
use {hdlskel_lib}.basic_pkg.all;
use {hdlskel_lib}.vec_pkg.all;

use {hdlskel_lib}.ramface_pkg.all;
use {hdlskel_lib}.skmap_pkg.all;
use {hdlskel_lib}.skmap_map_acc_pkg.all;

use {hdlskel_lib}.skmap_module_ipkg;
""");

        #write module entity declaration begining
        vhdl_f.write(f"""
entity {recipe.fw_module} is
  generic (
    BASE_ADDR       : natural;
    SKMAP_KIDS : integer_vector := NULL_INTEGER_VECTOR;
    SKMAP_BYTE_ALIGN : integer := SKMAP_MAP_ACC_BYTE_ALIGN_TO_REG;

    RAMFACE_ADDR_W  : natural;
    RAMFACE_DATA_W  : natural;
    RAMFACE_WREN_W  : natural := RAMFACE_DATA_W/8;
    RAMFACE_LATENCY : natural := skmap_module_ipkg.RAMFACE_LATENCY""");
        if len(recipe.k) > 0:
            vhdl_f.write(";\n")
        for ii, kv in enumerate(recipe.k):
            if kv.t.kind == ValueKind.flag:
                assert kv.flags is not None
                for jj, f in enumerate(kv.flags):
                    if f.vec_len != None:
                        vhdl_t = f'boolean_vector(0 to {f.vec_len}-1)'
                    else:
                        vhdl_t = 'boolean'
                    vhdl_f.write(f'\n    {f.name} : {vhdl_t}')
                    if jj != len(kv.flags)-1: vhdl_f.write(";")

            else:
                vhdl_t = k_type_to_vhdl_str(kv.t, basic_ports=basic_ports)
                vhdl_f.write(f'\n    {kv.name} : {vhdl_t}')
            if ii != len(recipe.k)-1: vhdl_f.write(";")
        vhdl_f.write(f"""
  );
  port (
    clk_i : in  std_ulogic;

    ramface_ce_i : in std_ulogic := '1';""")

        if basic_ports:
            vhdl_f.write(f"""
    ramface_rqst_en_i   : in  std_ulogic;
    ramface_rqst_addr_i : in  std_ulogic_vector(RAMFACE_ADDR_W-1 downto 0);
    ramface_rqst_wren_i : in  std_ulogic_vector(RAMFACE_WREN_W-1 downto 0);
    ramface_rqst_data_i : in  std_ulogic_vector(RAMFACE_DATA_W-1 downto 0);
    ramface_rply_en_o   : out std_ulogic;
    ramface_rply_fail_o : out std_ulogic;
    ramface_rply_data_o : out std_ulogic_vector(RAMFACE_DATA_W -1 downto 0)""")
        else:
            vhdl_f.write(f"""
    ramface_rqst_i : in ramface_rqst_t(
      addr(RAMFACE_ADDR_W-1 downto 0),
      wren(RAMFACE_WREN_W-1 downto 0),
      data(RAMFACE_DATA_W-1 downto 0)
    );
    ramface_rply_o : out ramface_rply_t(
      data(RAMFACE_DATA_W -1 downto 0)
    )""")

        if len(recipe.var) > 0:
            vhdl_f.write(";\n")
        for ii, varv in enumerate(recipe.var):
            #TODO: access types
            assert varv.acc != Acc.na
            output = varv.acc.sw_writable
            # assert output is not None
            varv.direction = "out" if output else "in"

            # name = varv.name
            # assert not name.endswith(port_ext_bad)
            # if not name.endswith(port_ext):
            #     name += port_ext
            # varv.name_ext = name

            if varv.flags is not None:
                varv.name_ext = var_name(varv.name)
                varv.uses_var_name = True
                for jj, f in enumerate(varv.flags):
                    f.name_ext = port_name(f.name, varv.direction)
                    if f.is_vec:
                        rng = f"({f.vec_len}-1 downto 0)"
                        vhdl_t = f'std_logic_vector{rng}'
                    else:
                        vhdl_t = f'std_logic'
                    vhdl_f.write(f'\n    {f.name_ext} : {varv.direction} {vhdl_t}')
                    if jj != len(varv.flags)-1: vhdl_f.write(";")
            else:
                varv.name_ext = port_name(varv.name, varv.direction)
                varv.uses_var_name = False
                if varv.acc in (Acc.wt, Acc.rc):
                    # print(f'{varv.t=}')
                    if varv.t.is_vec:
                        rng = f"({varv.t.vec_len}-1 downto 0)"
                        vhdl_t = f'std_logic_vector{rng}'
                    else:
                        vhdl_t = f'std_logic'
                    if varv.acc == Acc.wt:
                        name_port = port_name_trig(varv.name_ext)
                    else:
                        assert varv.acc == Acc.rc
                        name_port = port_name_clear(varv.name_ext)
                    vhdl_f.write(f'\n    {name_port} : out {vhdl_t};')

                vhdl_t = var_type_to_vhdl_str(varv.t, basic_ports=basic_ports)
                vhdl_f.write(f'\n    {varv.name_ext} : {varv.direction} {vhdl_t}')
            if ii != len(recipe.var)-1: vhdl_f.write(";")
        vhdl_f.write(f"""
  );
end entity;

architecture rtl of {recipe.name} is

  alias BYTE_ALIGN is SKMAP_BYTE_ALIGN;\n""")

        for kv in recipe.k:
            if kv.t.kind == ValueKind.flag:
                vhdl_f.write(f"""
  function get_{kv.name} return boolean_vector is
    variable flags : boolean_vector(0 to {kv.t.width}-1) := (others => false);
  begin\n""")
                # vhdl_f.write(f'  constant {kv.name} : boolean_vector(0 to {kv.t.width}-1) := ( ');
                assert kv.flags is not None
                for ii, f in enumerate(kv.flags):
                    if f.vec_len != None:
                        vhdl_f.write(f'    flags({f.bit} to {f.bit} + {f.vec_len} - 1) := {f.name};\n')
                    else:
                        vhdl_f.write(f'    flags({f.bit}) := {f.name};\n')
                vhdl_f.write(f"""    return flags;
  end function;
  constant {kv.name} : boolean_vector := get_{kv.name};\n """)
                        

        vhdl_f.write(regs_len_str(recipe.k, 'REGS_K_INT_LEN', k = True));

        vhdl_f.write(f"""
  function get_REGS_K_INT return integer_vector is
    variable k_vec_int : integer_vector(0 to REGS_K_INT_LEN-1) := (others => 0);
    variable byte_idx : integer := 0;
  begin\n""")
    # variable offset_v : integer := 0;
        # for ii in range(total_k_with_fixed_idx):
        #     kv = recipe.k[ii]
        for kv in recipe.k:
            if kv.t.kind == ValueKind.flag:
                vhdl_f.write(f"    skmap_map_acc_k(k_vec_int_io=>k_vec_int, byte_idx_io=>byte_idx, flags_i=>{kv.name});\n")
            else:
                if(kv.t.width > 32):
                   raise RuntimeError(f"Currently k must support 32bit integers {kv.t.width=} {kv.t.kind=}")

                is_signed_str = 'TRUE' if kv.t.kind == ValueKind.sint else 'FALSE'
                vhdl_f.write(f"    skmap_map_acc_k(k_vec_int_io=>k_vec_int, byte_idx_io=>byte_idx, val_i=>{kv.name}, w_i=>{kv.t.width}, signed_i=>{is_signed_str});\n")
                # name = kv.name
                # if addr_byte % 4 == 0:
                #     if addr_byte != 0: vhdl_f.write(f",\n")
                #     vhdl_f.write(f"    {addr_byte//4} => {name}")
                # else:
                #     if ((addr_byte + kv.t.width//8) % 4) == 0:
                #         if kv.t.width == 8:
                #             name = f"to_sint8({name})"
                #         elif kv.t.width == 16:
                #             name = f"to_sint16({name})"
                #     vhdl_f.write(f" + {name} *2**{(addr_byte % 4)*8}")
        vhdl_f.write("    return k_vec_int;\n  end function;\n\n")
        # arecipe.k:

        vhdl_f.write(regs_len_str(recipe.var, 'REGS_VAR_LEN'))
  #       vhdl_f.write(f"""
  # function get_REGS_VAR_LEN return natural is
  #   variable byte_idx : natural := 0;
  # begin\n""")
  #       for varv in recipe.var:
  #           vhdl_f.write(f"    skmap_map_acc_byte_inc(byte_idx, VAL_W=>{varv.t.width},")
  #           vhdl_f.write("BYTE_ALIGN=>BYTE_ALIGN")
  #           if varv.t.is_vec:
  #               vhdl_f.write(f", VEC_LEN=>{varv.t.vec_len}");
  #           vhdl_f.write(f"); -- {varv.name}\n")
  #       vhdl_f.write(f"""    return ceil_div(byte_idx, 4);
  # end function;
  # constant REGS_VAR_LEN : natural := get_REGS_VAR_LEN;\n""")
        vhdl_f.write(f"""

  signal regs_var_rd_data : vec_slv32_t(0 to REGS_VAR_LEN-1) := (others => (others => '0'));
  signal regs_var_wr_data : vec_slv32_t(0 to REGS_VAR_LEN-1);
  signal regs_var_wr_wren : vec_slv4_t (0 to REGS_VAR_LEN-1);

begin
\n""")
        for kv in recipe.k:
            if kv.t.kind == ValueKind.flag:
                continue
            if kv.t.is_vec:
                # TODO: add type checking for vectors
                continue
            if kv.t.kind == ValueKind.uint:
                vhdl_f.write(f'assert {kv.name} < 2**{kv.t.width} severity FAILURE;\n')
            elif kv.t.kind == ValueKind.sint and kv.t.width <= 32:
                vhdl_f.write(f'assert {kv.name} <   2**{kv.t.width-1} severity FAILURE;\n')
                vhdl_f.write(f'assert {kv.name} >= -2**{kv.t.width-1} severity FAILURE;\n')

        vhdl_f.write(f"""
  i_skmap_module : entity {hdlskel_lib}.skmap_module
  generic map (
    SKMAP_ID           => "{recipe.id}",
    SKMAP_VERSION      => {recipe.version},
    SKMAP_CHECKSUM     => 16#{recipe.checksum_str()}#,
    SKMAP_KIDS         => SKMAP_KIDS,
    SKMAP_BYTE_ALIGN   => SKMAP_BYTE_ALIGN,
    BASE_ADDR          => BASE_ADDR,
    RAMFACE_ADDR_W     => RAMFACE_ADDR_W,
    RAMFACE_DATA_W     => RAMFACE_DATA_W,
    RAMFACE_WREN_W     => RAMFACE_WREN_W,
    RAMFACE_LATENCY    => RAMFACE_LATENCY,
    REGS_K_INT         => get_REGS_K_INT,
    REGS_VAR_LEN       => REGS_VAR_LEN
  ) port map (
    clk_i              => clk_i,

    ramface_ce_i       => ramface_ce_i,""")
        if basic_ports:
            vhdl_f.write(f"""
    ramface_rqst_i.en   => ramface_rqst_en_i,
    ramface_rqst_i.addr => u_unsigned(ramface_rqst_addr_i),
    ramface_rqst_i.wren => ramface_rqst_wren_i,
    ramface_rqst_i.data => ramface_rqst_data_i,
    ramface_rply_o.en   => ramface_rply_en_o,
    ramface_rply_o.fail => ramface_rply_fail_o,
    ramface_rply_o.data => ramface_rply_data_o,
""")
        else:
            vhdl_f.write(f"""
    ramface_rqst_i     => ramface_rqst_i,
    ramface_rply_o     => ramface_rply_o,
""")
        vhdl_f.write(f"""
    regs_var_wr_wren_o => regs_var_wr_wren,
    regs_var_wr_data_o => regs_var_wr_data,
    regs_var_rd_data_i => regs_var_rd_data
  );

  process(all)
    variable byte_idx_v : natural;
""")
        for varv in recipe.var:
            if varv.uses_var_name:
                vhdl_t = var_type_to_vhdl_str(varv.t)
                vhdl_f.write(f'    variable {varv.name_ext} : {vhdl_t};')
        vhdl_f.write("""
  begin
    byte_idx_v := 0;\n\n""");
        for varv in recipe.var:
            if varv.uses_var_name:
                if varv.direction == "in":
                    assert( varv.flags is not None )
                    assert( not varv.t.is_vec) # TODO: support vec of flags
                    for f in varv.flags:
                        if f.is_vec:
                            vhdl_f.write(f'    {varv.name_ext}({f.vec_len} -1 + {f.bit} downto {f.bit}) := {f.name_ext};\n')
                        else:
                            vhdl_f.write(f'    {varv.name_ext}({f.bit}) := {f.name_ext};\n')
                    vhdl_f.write('\n')

        align_str = "BYTE_ALIGN=>BYTE_ALIGN"
        for varv in recipe.var:
            match varv.acc:
                case Acc.ro:
                    vhdl_f.write(f'    skmap_map_acc_ro(regs_var_rd_data, byte_idx_v, {varv.name_ext}, {align_str});\n')
                case Acc.rw:
                    skmap_func = 'skmap_map_acc_rw_var' if varv.uses_var_name else 'skmap_map_acc_rw'
                    vhdl_f.write(f'    {skmap_func}(regs_var_rd_data, regs_var_wr_data, byte_idx_v, {varv.name_ext}, {align_str});\n')
                case Acc.wt:
                    name_trig = port_name_trig(varv.name_ext)
                    skmap_func = 'skmap_map_acc_wt_var' if varv.uses_var_name else 'skmap_map_acc_wt'
                    vhdl_f.write(f'    skmap_map_acc_wt(regs_var_rd_data, regs_var_wr_data, regs_var_wr_wren, byte_idx_v, {varv.name_ext}, {name_trig}, {align_str});\n');
                case Acc.rc:
                    if varv.t.kind == ValueKind.flag:
                        vhdl_f.write(f"""    if rising_edge(clk_i) then
      skmap_map_acc_rc_flags(regs_var_rd_data, regs_var_wr_wren, byte_idx_v, {varv.name_ext}, {align_str});
    else
      skmap_map_acc_byte_inc(byte_idx_v, {varv.name_ext}'length, {align_str});
    end if;\n""");
                    else:
                        name_clear = port_name_clear(varv.name_ext)
                        vhdl_f.write(f'    skmap_map_acc_rc(regs_var_rd_data, regs_var_wr_wren, byte_idx_v, {varv.name_ext}, {name_clear}, {align_str});\n');
                case _:
                    print(f'ERROR {varv.acc=}')
                    assert(False)
            vhdl_f.write("")
        vhdl_f.write("\n")

        for varv in recipe.var:
            if varv.uses_var_name:
                if varv.direction == "out":
                    assert( varv.flags is not None )
                    assert( not varv.t.is_vec) # TODO:
                    for f in varv.flags:
                        if f.is_vec:
                            vhdl_f.write(f'    {f.name_ext} <= {varv.name_ext}({f.vec_len} -1 + {f.bit} downto {f.bit});\n')
                        else:
                            vhdl_f.write(f'    {f.name_ext} <= {varv.name_ext}({f.bit});\n')
                    vhdl_f.write('\n')
        vhdl_f.write("""  end process;

end architecture;
""");


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse a skmap module recipe file and generate skmap module"
    )
    parser.add_argument(
        "recipe_file",
        type=Path,
        help="Path to skmap recipe file"
    )
    parser.add_argument(
        "vhdl_file",
        type=Path,
        help="Path to VHDL file to generate"
    )
    return parser.parse_args()


def main():
    args = parse_args()
    generate_vhdl_module(args.recipe_file, args.vhdl_file) 

if __name__ == '__main__':
    main()
