//-------------------------------------------------------------------------------
// NOTE: this file is autogenerated:
//    * From /mnt/c/Users/pevha/wsl/github/hdlskel/pip/skmap/src/skmap/code_generator_cpp.py
//    * On 2026-09-27 04:54:38.279645 
//    * Using HDLSkel SkMap v1.1.0
//    * For test_skmap_tree_module TBTrMod v1
//    * Checksum 0x1AD7
//-------------------------------------------------------------------------------
#include "hdlskel/skmap/basic_types.hpp"
#include "hdlskel/skmap/reg.hpp"
#include "hdlskel/skmap/module.hpp"
#include "hdlskel/skmap/recipe_functions.hpp"

#include <cassert>
#include <cmath>
#include <memory>
#include <string>
#include <vector>

namespace hdlskel::skmap::autogen {

class TestSkmapTreeModule : public skmap::Module {
public:
    static std::string class_name() { return "test_skmap_tree_module"; }
    static id_t class_id() {
        const static id_t id = id_str_to_id("TBTrMod");
        return id;
    };
    constexpr static version_t   class_version   = 1;
    constexpr static checksum_t  class_checksum  = 0x1AD7;

    std::string        name()     const override { return TestSkmapTreeModule::class_name(); }
    id_t        id()       const override { return TestSkmapTreeModule::class_id(); }
    version_t   version()  const override { return TestSkmapTreeModule::class_version; }
    checksum_t  checksum() const override { return TestSkmapTreeModule::class_checksum; }

    static int  skmap_ver_major() { return skmap::ver_major; }
    static int  skmap_ver_minor() { return skmap::ver_minor; }
    static int  skmap_ver_patch() { return skmap::ver_patch; }
    static std::string skmap_ver_str() { return skmap::ver_str; }

    static bool registered;
    //TREE_DEPTH: Tree depth
    std::shared_ptr<Reg> TREE_DEPTH_inst() const { return m_k_TREE_DEPTH; }
    uint_t TREE_DEPTH() const { return m_k_TREE_DEPTH->read_uint_cached(); }
    //TREE_WIDTH: Tree width
    std::shared_ptr<Reg> TREE_WIDTH_inst() const { return m_k_TREE_WIDTH; }
    uint_t TREE_WIDTH() const { return m_k_TREE_WIDTH->read_uint_cached(); }
    //trigger_flags: Trigger asserts
    std::shared_ptr<Reg> trigger_flags_inst() const { return m_var_trigger_flags; }
    uint_t trigger_flags_read_cached() const { return m_var_trigger_flags->read_uint_cached(); }
    uint_t trigger_flags_read() { return m_var_trigger_flags->read_uint(); }
    void trigger_flags_write_trigger( uint_t value ) { m_var_trigger_flags->write_uint(value); }
    //flags: RC flags
    std::shared_ptr<RegFlags> flags_inst() const { return m_var_flags; }
    void flags_update_cache() { m_var_flags->update_cache(); }
    void flags_clear() { m_var_flags->write_zero(); }
    bool flag_debug_read_cached() const { return m_var_flag_debug->read_bool_cached(); }
    bool flag_debug_read() { return m_var_flag_debug->read_bool(); }
    bool flag_info_read_cached() const { return m_var_flag_info->read_bool_cached(); }
    bool flag_info_read() { return m_var_flag_info->read_bool(); }
    bool flag_warn_read_cached() const { return m_var_flag_warn->read_bool_cached(); }
    bool flag_warn_read() { return m_var_flag_warn->read_bool(); }
    bool flag_error_read_cached() const { return m_var_flag_error->read_bool_cached(); }
    bool flag_error_read() { return m_var_flag_error->read_bool(); }
    bool flag_fatal_read_cached() const { return m_var_flag_fatal->read_bool_cached(); }
    bool flag_fatal_read() { return m_var_flag_fatal->read_bool(); }

protected:
    void init_reg_map_k()   override;
    void init_reg_map_var() override;

    virtual std::shared_ptr<Module> make_empty() const override {
        return std::make_shared<TestSkmapTreeModule>();
    };

private:
    std::shared_ptr<Reg> m_k_TREE_DEPTH;
    std::shared_ptr<Reg> m_k_TREE_WIDTH;
    std::shared_ptr<Reg> m_var_trigger_flags;
    std::shared_ptr<RFlag> m_var_flag_debug;
    std::shared_ptr<RFlag> m_var_flag_info;
    std::shared_ptr<RFlag> m_var_flag_warn;
    std::shared_ptr<RFlag> m_var_flag_error;
    std::shared_ptr<RFlag> m_var_flag_fatal;
    std::shared_ptr<RegFlags> m_var_flags;
};

}
