name = "recipe_test_bench_module"
sw_module = "RecipeTestBenchModule"
fw_module = "recipe_test_bench_module"
id = "TBRecip"
version = 1
# fw_opts = {ports_use_basic_types = true, hdlskel_vhdl_lib='work'}
fw_opts = { size_reserved=0x1000 }

ipkg = [
  # {name = "INT_11", value = 11 },
  # {name = "INT_3", value = 3 },
  # {name = "INT_33", value = "{INT11}*{INT3}" },
  {name = "INT_33", value = 33 },
  {name = "STR_TESTING", value = "TESTING" }
]

k = [
  {name = "RO_LEN",   t = "u8", desc = "RO length"},
  {name = "RO_VAL_W", t = "u8", desc = "RO value width"},
  {name = "RW_LEN",   t = "u8", desc = "RW length"},
  {name = "RW_VAL_W", t = "u8", desc = "RW value width"},
  {name = "MEM_RW_VAL_W", t = "u8", desc = "MEM RW value width"},
  {name = "MEM_RW_LEN", t = "u8", desc = "MEM RW length"},
  {name = "MEM_RW_LATENCY", t = "u8", desc = "MEM RW latency"},
  {name = "MEM_RO_VAL_W", t = "u8", desc = "MEM RO width"},
  {name = "MEM_RO_LEN", t = "u8", desc = "MEM RO length"},
  {name = "MEM_RO_LATENCY", t = "u8", desc = "MEM RO latency"},
  {name = "FLAGSK",    t = "b", desc = "K Flags", flags = [
     # { name = "FLAGK0", desc = "FlagK 0", vec_len = "{RO_VAL_W}"},
     { name = "FLAGK1", ass = "debug",   desc = "FlagK 1"},
     { name = "FLAGK2", ass = "warn",   desc = "FlagK 2"},
  ]}
]

var = [
  {name = "bit_bool_rc",  t = "b1", acc = "rc", desc = "Flag single"},
  {name = "bit_bool_rw",  t = "b1", acc = "rw", desc = "Flag single"},
  {name = "bit_bool_wt",  t = "b1", acc = "wt", desc = "Flag single"},
  {name = "bit_ro",  t = "x1", acc = "rc", desc = "Flag single"},
  {name = "bit_wt",  t = "x1", acc = "rw", desc = "Flag single"},
  {name = "ctrl_flags",    t = "b", acc = "rw", desc = "RC flags", flags = [
     { name = "ctrl_flag_0", bit = 0, desc = "ctrl_flag 0"},
     { name = "ctrl_flag_8", bit = 8, desc = "ctrl_flag 8"},
     { name = "ctrl_flag_16_vec", bit = 16, desc = "ctrl_flag_vec 16", vec_len = 5},
  ]},
  {name = "regs_ro",  t = "s{RO_VAL_W}[{RO_LEN}]", acc = "ro", desc = "RO registers"},
  {name = "regs_rw",  t = "s{RW_VAL_W}[{RW_LEN}]", acc = "rw", desc = "RW registers"},
  {name = "regs_wt",  t = "x5", acc = "wt", desc = "WT registers"},
  {name = "regs_rc",  t = "s{RW_VAL_W}[{RW_LEN}]", acc = "rc", desc = "RC registers"},
  # {name = "reg_s_wt",  t = "s40", acc = "wt", desc = "RC registers"},
  {name = "reg_s_rc",  t = "s{INT_33}", acc = "rc", desc = "RC registers"},
  {name = "flags",    t = "b", acc = "rc", desc = "RC flags", flags = [
     { name = "debug_flag0", ass = "debug", desc = "Flag 0"},
     { name = "info_flag1", ass = "info",  desc = "Flag 1"},
     { name = "warn_flag2", ass = "warn",  desc = "Flag 2"},
     { name = "error_flag3", ass = "error", desc = "Flag 3"},
     { name = "fatal_flag4", ass = "fatal", desc = "Flag 4"},
     { name = "debug_flag_vec", ass = "debug", desc = "Flag vec", vec_len=3},
   ]}
]
mem = [
  {name = "mem_rw", t="u{MEM_RW_VAL_W}[{MEM_RW_LEN}]", acc="rw", desc = "RW Memory", fw_depth = "{MEM_RW_LEN}", fw_width = "{MEM_RW_VAL_W}",fw_latency = "{MEM_RW_LATENCY}" },
  {name = "mem_ro", t="u{MEM_RO_VAL_W}[{MEM_RO_LEN}]", acc="ro", desc = "RO Memory", fw_depth = "{MEM_RO_LEN}", fw_width = "{MEM_RO_VAL_W}",fw_latency = "{MEM_RO_LATENCY}" }
]
