name = "recipe_test_bench_module"
sw_module = "RecipeTestBenchModule"
fw_module = "recipe_test_bench_module"
id = "TBRecip"
version = 1
# fw_opts = {ports_use_basic_types = true, hdlskel_vhdl_lib='work'}
# fw_opts = { hdlskel_vhdl_lib='work'}

k = [
  {name = "RO_LEN",   t = "u8", desc = "RO length"},
  {name = "RO_VAL_W", t = "u8", desc = "RO value width"},
  {name = "RW_LEN",   t = "u8", desc = "RW length"},
  {name = "RW_VAL_W", t = "u8", desc = "RW value width"},
  {name = "FLAGSK",    t = "b", desc = "K Flags", flags = [
     # { name = "FLAGK0", desc = "FlagK 0", vec_len = "{RO_VAL_W}"},
     { name = "FLAGK1", ass = "debug",   desc = "FlagK 1"},
     { name = "FLAGK2", ass = "warn",   desc = "FlagK 2"},
  ]}
]

var = [
  {name = "ctrl_flags",    t = "b", acc = "rw", desc = "RC flags", flags = [
     { name = "ctrl_flag_0", bit = 0, desc = "ctrl_flag 0"},
     { name = "ctrl_flag_8", bit = 8, desc = "ctrl_flag 8"},
     { name = "ctrl_flag_16_vec", bit = 16, desc = "ctrl_flag_vec 16", vec_len = 5},
  ]},
  {name = "regs_ro",  t = "s{RO_VAL_W}[{RO_LEN}]", acc = "ro", desc = "RO registers"},
  {name = "regs_rw",  t = "s{RW_VAL_W}[{RW_LEN}]", acc = "rw", desc = "RW registers"},
  {name = "regs_wt",  t = "x5", acc = "wt", desc = "WT registers"},
  {name = "regs_rc",  t = "s{RW_VAL_W}[{RW_LEN}]", acc = "rc", desc = "RC registers"},
  # {name = "reg_s_wt",  t = "s40", acc = "wt", desc = "RC registers"},
  {name = "reg_s_rc",  t = "s33", acc = "rc", desc = "RC registers"},
  {name = "flags",    t = "b", acc = "rc", desc = "RC flags", flags = [
     { name = "debug_flag0", ass = "debug", desc = "Flag 0"},
     { name = "info_flag1", ass = "info",  desc = "Flag 1"},
     { name = "warn_flag2", ass = "warn",  desc = "Flag 2"},
     { name = "error_flag3", ass = "error", desc = "Flag 3"},
     { name = "fatal_flag4", ass = "fatal", desc = "Flag 4"},
     { name = "debug_flag_vec", ass = "debug", desc = "Flag vec", vec_len=3},
   ]}
]
